INSERT INTO markdown_skus (style_code, colour, product_title, source_url, status)
VALUES
('ALYX', 'ESPRESSO SUEDE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('AMAR', 'TAUPE SUEDE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('ANJA', 'VINO SUEDE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('ASTI', 'ESPRESSO SUEDE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('ASTI', 'ESPRESSO PATENT', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('BAKER', 'VINO NAPPA PATENT', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('BAKER', 'BLACK NAPPA PATENT', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('BAKER', 'STONE NAPPA PATENT', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('BIANCA', 'CEMENTO SUEDE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('BLAIRE', 'ESPRESSO SUEDE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('BLAIRE', 'BLACK SUEDE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('CAMEO', 'ECRU SNAKE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('CAMILLE', 'BLACK VINTAGE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('CAMILLE', 'TAN VINTAGE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('CAMILLE', 'VANILLA VINTAGE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('CHARLI', 'BLACK NAPPA', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('CITY', 'BLACK NAPPA', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('CITY', 'DOVE NAPPA', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('CITY', 'SKY NAPPA', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('CONNIE', 'ASHEN SUEDE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('CONNIE', 'ESPRESSO SUEDE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('CONNIE', 'TAUPE SUEDE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('CUBA', 'LATTE NAPPA', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('DANI', 'BLACK HI SHINE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('DELIA', 'BLACK HI SHINE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('DELIA', 'BLACK COMO', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('DEMI', 'BLACK HI SHINE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('ERES', 'BLACK HI SHINE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('FARRAH', 'CHOC VINTAGE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('FARRAH', 'TAN VINTAGE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('FARRAH', 'BLACK VINTAGE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('FIFI', 'SKIN CAPRETTO', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('FIFI', 'TAUPE SUEDE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('FIFI', 'CHOC CROCO', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('FREYA', 'BLACK VINTAGE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('FREYA', 'SKIN CAPRETTO', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('FREYA', 'DOVE NAPPA', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('GLACIER', 'BLACK VINTAGE/SHEARLING', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('GLACIER', 'CHOC VINTAGE/SHEARLING', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('GLANCE', 'TAN VINTAGE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('GLORIA', 'STONE SUEDE/SHEARLING', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('GLORIA', 'ESPRESSO SUEDE/SHEARLING', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('GLORIA', 'VANILLA VINTAGE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('GOMEZ', 'SKY NAPPA', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('GOMEZ', 'VANILLA VENICE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('GOMEZ', 'ESPRESSO SUEDE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('GRAND', 'CHOC VINTAGE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('HAYES', 'ESPRESSO SUEDE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('HAYES', 'BLACK COMO', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('ISABEL', 'BLACK MAGIC', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('JASPER', 'BISQUE SCUBA', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('JERRY', 'BLACK RUFFLE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('JERRY', 'BISQUE RUFFLE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('JETTA', 'CHOC TUSCON', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('JETTA', 'BLACK TUSCON', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('JETTA', 'TAN TUSCON', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('JUNIPER', 'BLACK VENICE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('JUNIPER', 'SKY NAPPA', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('JUNIPER', 'BLACK ANGUILLE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('LILA', 'STEEL NUBUCK', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('LILA', 'SKY NUBUCK', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('LILA', 'BLUSH NUBUCK', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('LILA', 'TOMATO NUBUCK', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('LILA', 'BLACK NUBUCK', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('LILA', 'ESPRESSO NUBUCK', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('LILA', 'BLACK TURIN', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('LUCA', 'MILK CAPRETTO', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('LUXURY', 'BLACK CROCO', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('LUXURY', 'CHOC CROCO', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('LUXURY', 'CHOC VINTAGE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('MARCEL', 'DOVE NAPPA', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('MARCEL', 'SILVER NAPPA METALLIC', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('MARCEL', 'CLEAR VINYLITE/SKIN', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('MARCEL', 'BLACK PATENT', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('MARCEL', 'BLACK NAPPA', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('MARCEL', 'GOLD NAPPA METALLIC', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('MARCY', 'GOLD FOIL', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('MARCY', 'BLACK PATENT', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('MATRIX', 'ECRU SNAKE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('MATRIX', 'CEMENTO SUEDE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('MIKA', 'BLACK JERSEY', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('MOTIF', 'BLACK JERSEY/BLACK', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('MOTIF', 'BLACK JERSEY/BLACK WHITE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('MOTIF', 'WHITE JERSEY/WHITE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('MOTION', 'BLACK PATENT', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('MOTION', 'WHITE PATENT', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('NIKI', 'VANILLA VINTAGE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('PENELOPE', 'CHOC VALENCIA', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('PHOEBE', 'BLACK NAPPA', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('PHOEBE', 'CHOCOLATE NAPPA', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('PORSHA', 'VESTRA VALENCIA', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('PRESH', 'DOVE NAPPA', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('PRESH', 'BLACK NAPPA', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('REMI', 'ESPRESSO SUEDE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('SAGE', 'GOLD NAPPA METALLIC', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('SAGE', 'SKIN NAPPA', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('SAGE', 'BLACK NAPPA', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('SAINT', 'TAN VINTAGE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('SAINT', 'BLACK VINTAGE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('SAINT', 'CHOC VINTAGE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('SANDRA', 'CHOC CROCO', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('SANDRA', 'VINO CROCO', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('SICILY', 'WHEAT SUEDE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('SKYE', 'WHITE NAPPA', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('SKYE', 'BLACK PATENT', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('SOFIA', 'IVORY BROCADE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('STARR', 'TAN NAPPA', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('STARR', 'BLACK NAPPA', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('TRIBUTE', 'BLACK COMO', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('VICTORIA', 'WHEAT SUEDE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('VICTORIA', 'ESPRESSO SUEDE', 'User-provided markdown list', 'manual://markdown-removal', 'deleted'),
('VIOLET', 'BRONZE NAPPA METALLIC', 'User-provided markdown list', 'manual://markdown-removal', 'deleted')
ON DUPLICATE KEY UPDATE
  product_title = VALUES(product_title),
  source_url = VALUES(source_url),
  status = 'deleted',
  updated_at = CURRENT_TIMESTAMP;